name: 'ZEIT Now - Deploy'
description: 'Deploy a project using ZEIT Now.'

inputs:

  path: 
    description: 'The project path.'
    required: false

  prod:
    description: 'Create a production deployment'
    required: false
    default: true

  token:
    description: 'The ZEIT token.'
    required: true

outputs:
  url:
    description: 'The URL that the project was deployed to.'

runs:
  using: 'node12'
  main: 'index.js'
